services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    LivingWorld\Import\ImportCommand:
        tags:
          - 'console.command'

    LivingWorld\Generate\GenerateWorldCommand:
        tags:
          - 'console.command'
