services:

    monolog.rotating.file.handler:
        class: Monolog\Handler\RotatingFileHandler
        arguments:
            - '%tmp.dir%/logger.log'

    monolog.logger:
        class: Monolog\Logger
        arguments:
            - 'default'
            - ['@monolog.rotating.file.handler']

    logger:
        class: LivingWorld\Logger\ImportProcessorLogger
        arguments:
            - '@monolog.logger'

    random.organism.type.getter:
        class: LivingWorld\Generate\XmlFile\Structure\Organism\RandomOrganismTypeGetter

    world.structure.generator:
        class: LivingWorld\Generate\XmlFile\WorldStructureGenerator
        arguments:
            - '@random.organism.type.getter'

    command.argument.getter:
        class: LivingWorld\Command\Argument\CommandArgumentGetter

    xml.file.getter:
        class: LivingWorld\Generate\XmlFile\XmlFileGetter

    file.content_getter:
        class: LivingWorld\File\FileContentGetter

    file.file_writer:
        class: LivingWorld\File\FileWriter
        arguments:
            - '%tmp.dir%'

    xml.file.parser:
        class: LivingWorld\Import\XmlFile\XmlFileParser
        arguments:
            - '%tmp.dir%'
            - '@file.content_getter'

    organism.type.formatter:
        class: LivingWorld\Graphics\OrganismTypeFormatter

    organism.output.formatter:
        class: LivingWorld\Graphics\OrganismOutputFormatter

    graphics.position.getter:
        class: LivingWorld\Graphics\Screen\Position\PositionContentGetter
        arguments:
            - '@organism.type.formatter'

    screen.writer:
        class: LivingWorld\Graphics\Screen\ScreenWriter
        arguments:
            - '@graphics.position.getter'

    frame.facade:
        class: LivingWorld\Graphics\Frame\FrameFacade

    import.processor.birth_processor:
        class: LivingWorld\Import\Processor\LifeCycle\BirthProcessor

    import.processor.die_processor:
        class: LivingWorld\Import\Processor\LifeCycle\DieOrSurviveProcessor
        arguments:
            - '@frame.facade'

    import.processor.lifecycle_storage:
        class: LivingWorld\Import\Processor\LifeCycle\Resolve\LifeCycleProcessorStorage
        arguments:
            - ['@import.processor.die_processor', '@import.processor.birth_processor']

    import.processor.lifecycle_resolver:
        class: LivingWorld\Import\Processor\LifeCycle\Resolve\LifeCycleProcessorResolver
        arguments:
            - '@import.processor.lifecycle_storage'

    import.file.processor:
        class: LivingWorld\Import\Processor\ImportFileProcessor
        arguments:
            - '@import.processor.lifecycle_resolver'
            - '@logger'

    world.structure.getter:
        class: LivingWorld\Import\XmlFile\Output\WorldStructureGetter

    import.command:
        class: LivingWorld\Import\ImportCommand
        arguments:
            - '@command.argument.getter'
            - '@organism.output.formatter'
            - '@xml.file.parser'
            - '@screen.writer'
            - '@import.command.facade'

    import.command.facade:
        class: LivingWorld\Import\ImportCommandFacade
        arguments:
            - '@import.file.processor'
            - '@world.structure.getter'
            - '@xml.file.getter'
            - '@file.file_writer'

    generate.world.command:
        class: LivingWorld\Generate\GenerateWorldCommand
        arguments:
            - '@command.argument.getter'
            - '@world.structure.generator'
            - '@xml.file.getter'
            - '@file.file_writer'
